// SolidFind mobile — Pro guidelines (desktop LEGAL_PRO content, About-page text treatment)
function MobileProGuidelines() {
  function mRich(text) {
    return text.split('**').map((part, i) => i % 2 === 1 ? <strong key={i}>{part}</strong> : <React.Fragment key={i}>{part}</React.Fragment>);
  }

  const CircleIcon = () => (
    <svg viewBox="0 0 20 20" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true">
      <circle cx="10" cy="10" r="8"/>
    </svg>
  );
  const StarIcon = () => (
    <svg viewBox="0 0 18 17" width="22" height="22" fill="currentColor" aria-hidden="true">
      <path d="M17.5,7.1c.4-.3.2-1-.3-1h-5.4c-.2,0-.4-.1-.5-.4l-1.7-5.2c-.2-.5-.8-.5-1,0l-1.7,5.2c0,.2-.3.4-.5.4H.9c-.5,0-.7.7-.3,1l4.4,3.2c.2.1.3.4.2.6l-1.7,5.2c-.2.5.4.9.8.6l4.4-3.2c.2-.1.4-.1.6,0l4.4,3.2c.4.3,1-.1.8-.6l-1.7-5.2c0-.2,0-.5.2-.6l4.4-3.2Z"/>
    </svg>
  );

  const tiers = [
    {
      icon: <CircleIcon/>,
      label: 'Free account',
      items: ['Company profile page', 'Up to 4 portfolio photos', 'Contact channels', 'Description & services', 'Searchable in all categories'],
    },
    {
      icon: <StarIcon/>,
      label: 'Pro account',
      items: ['Everything in Free', 'Priority placement in search results', 'Up to 12 portfolio photos or videos', 'Full analytics dashboard & profile views', 'Ad placement access across the platform', 'AI-ready profile formatting'],
    },
  ];

  // Desktop LEGAL_PRO sections rendered with About-page text treatment
  const sections = [
    {
      title: 'Nature of the Pro subscription',
      paras: [
        'The Pro subscription is a paid feature tier offered by SolidFind to professionals listed on the Platform. It provides access to enhanced profile tools and increased visibility within the Platform.',
        'The Pro subscription constitutes a service agreement between the Subscriber and SolidFind. It does not create any partnership, joint venture, agency relationship, endorsement, or verification of the Subscriber by SolidFind.',
      ],
    },
    {
      title: "What's included",
      intro: 'A Pro subscription provides access to the following features, as available at the time of subscription:',
      bullets: [
        'Priority placement in search results within the Subscriber\'s listed category, relative to non-Pro listings',
        'Visibility analytics — aggregated data on profile view activity, presented within the Platform dashboard',
        'Up to 12 project photos or videos displayed on the Subscriber\'s profile',
        'Ad placements across the Platform, subject to available inventory and the format and placement guidelines published by SolidFind from time to time',
        'Structured profile formatting optimised for AI-assisted search, where available',
      ],
      outro: 'SolidFind reserves the right to modify, add, or remove Pro features at any time. Where such changes materially affect the scope of the subscription, SolidFind will provide at least 14 days\' prior notice to active Subscribers.',
    },
    {
      title: 'Advertising placements',
      intro: 'Ad placements included in the Pro subscription are subject to the following conditions:',
      bullets: [
        'All advertising content must comply with SolidFind\'s content guidelines, as communicated from time to time.',
        'SolidFind retains full editorial discretion over the format, position, and scheduling of all ad placements on the Platform.',
        'Ad placements will be clearly labelled as advertising on the Platform.',
        'SolidFind does not guarantee a minimum number of impressions, views, or clicks generated by any ad placement.',
        'Ad placements are provided on an inventory-available basis.',
      ],
    },
    {
      title: 'Visibility & traffic — no guarantee',
      intro: 'SolidFind makes no guarantee of any of the following as a result of a Pro subscription:',
      bullets: [
        'A minimum number of profile views, page visits, or impressions',
        'A minimum number of enquiries, leads, or client contacts',
        'Any specific business outcome, contract, or revenue',
        'Any specific search ranking position',
      ],
      outro: 'Visibility and traffic levels depend on overall Platform activity, user behaviour, and other external factors outside SolidFind\'s control.',
    },
    {
      title: 'Credibility & professional status',
      intro: 'A Pro subscription does not alter, enhance, or imply any of the following:',
      bullets: [
        'Verification of the Subscriber\'s professional qualifications',
        'Confirmation of active licensing or regulatory compliance',
        'An endorsement of the quality of the Subscriber\'s work',
        'Any form of certification by SolidFind',
      ],
      outro: 'The credibility and reputation of a listed professional are determined exclusively by the accuracy and completeness of the information presented on their profile, and — where the reviews feature is active — by the reviews submitted by users. **Visibility can be improved. Credibility has to be earned.**',
    },
    {
      title: 'Subscriber obligations',
      intro: 'As a Pro Subscriber, you agree to:',
      bullets: [
        'Ensure that all information on your profile is accurate, current, and not misleading at all times',
        'Not use Pro features for any purpose that is unlawful, deceptive, or contrary to the SolidFind Terms & Conditions',
        'Not submit advertising content that is false, misleading, defamatory, or in breach of any applicable Indonesian law',
        'Notify SolidFind promptly if any material information on your profile changes',
      ],
      outro: 'SolidFind reserves the right to suspend or terminate a Pro subscription in the event of a material breach of these obligations or the general Terms & Conditions.',
    },
    {
      title: 'Billing, renewal & cancellation',
      paras: [
        'The Pro subscription is offered on a recurring basis — monthly or yearly. Subscriptions renew automatically at the end of each billing cycle unless cancelled prior to the renewal date.',
        'The Subscriber may cancel at any time. Cancellation takes effect at the end of the current billing period. Unless required by applicable law, subscription fees are non-refundable.',
        'SolidFind reserves the right to modify subscription pricing with at least 14 days\' prior written notice to active Subscribers.',
      ],
    },
  ];

  return (
    <div className="m-screen">
      <div className="m-about-hero" style={{ paddingBottom: 20 }}>
        <div className="m-topbar">
          <span className="m-brand"><img src="../../assets/solidfind-logo.svg" alt="SolidFind"/><span className="id">.id</span></span>
          <span className="m-topbar-sp"/>
          <button className="m-iconbtn" aria-label="Account">{I.user}</button>
          <button className="m-iconbtn" aria-label="Menu">{I.menu}</button>
        </div>
        <span className="m-eyebrow light" style={{ margin: '14px 20px 0' }}>For professionals</span>
        <h1>Pro guidelines</h1>
        <p>Everything in a free profile, plus the visibility tools companies use to be found and chosen. Visibility can be improved — credibility has to be earned.</p>
      </div>

      <div className="m-scroll">
        <button className="m-back">← Back</button>

        {/* Account tiers */}
        <div className="m-pad">
          <h2 className="m-h2">Account tiers</h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {tiers.map((t, i) => (
              <div className="m-acct-card" key={i} style={{ alignItems: 'flex-start' }}>
                <span style={{ color: 'var(--sf-orange)', opacity: 1, minWidth: 26, display: 'flex', alignItems: 'center', justifyContent: 'center', paddingTop: 2 }}>{t.icon}</span>
                <div>
                  <span className="m-eyebrow">{t.label}</span>
                  <ul style={{ margin: '8px 0 0', padding: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 5 }}>
                    {t.items.map(item => (
                      <li key={item} style={{ fontSize: 13, color: 'var(--sf-ink-soft)', display: 'flex', gap: 8 }}>
                        <span style={{ color: 'var(--sf-orange)', flexShrink: 0 }}>–</span>{item}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Desktop LEGAL_PRO sections */}
        {sections.map((s, si) => (
          <div className="m-pad" style={{ marginTop: 22 }} key={si}>
            <h2 className="m-h2"><span className="m-section-num">{si + 1}</span>{s.title}</h2>
            {s.intro && <div className="m-prose"><p><strong>{s.intro}</strong></p></div>}
            {s.bullets && <ul className="m-belief">{s.bullets.map((b, i) => <li key={i}>{mRich(b)}</li>)}</ul>}
            {s.paras && <div className="m-prose">{s.paras.map((p, i) => <p key={i}>{mRich(p)}</p>)}</div>}
            {s.outro && <div className="m-prose" style={{ marginTop: 10 }}><p>{mRich(s.outro)}</p></div>}
          </div>
        ))}

        <div className="m-pad" style={{ marginTop: 22, marginBottom: 28 }}>
          <div className="m-jump">
            <button style={{ opacity: 1 }}><b>Get Pro</b><span>Upgrade your company profile →</span></button>
            <button style={{ opacity: 1 }}><b>Terms and Conditions</b><span>Read our full legal terms →</span></button>
          </div>
        </div>

        <MFooter/>
      </div>
    </div>
  );
}

Object.assign(window, { MobileProGuidelines });
