import { mutation } from "./_generated/server";

const companies = [
  // CONSTRUCTION
  {
    name: "Balitecture",
    description: "Australian-owned villa developer offering end-to-end property development and management services in Bali. From design to construction to rental management.",
    category: "construction",
    subcategory: "residential",
    location: "Seminyak",
    address: "Jl. Raya Seminyak No.55, Seminyak, Kec. Kuta, Kabupaten Badung, Bali 80361",
    isPro: true,
    rating: 4.7,
    reviewCount: 42,
    projects: 85,
    teamSize: 35,
    projectSize: "shared", // 35 team members
    bookmarkCount: 58,
    viewsLastMonth: 1350,
    imageUrl: "https://ui-avatars.com/api/?name=Balitecture&size=200&background=f14110&color=fff&bold=true",
  },
  {
    name: "Bali Construction",
    description: "Luxury home, villa and commercial property builders with a dedicated team of architects, interior designers and contractors. Building dreams in paradise.",
    category: "construction",
    subcategory: "residential",
    location: "Denpasar",
    address: "Jl. Gatot Subroto Barat No.99, Pemecutan Klod, Kec. Denpasar Bar., Kota Denpasar, Bali 80119",
    isPro: true,
    rating: 4.5,
    reviewCount: 38,
    projects: 120,
    teamSize: 45,
    bookmarkCount: 45,
    viewsLastMonth: 1100,
    imageUrl: "/images/companies/bali-construction.png",
  },
  {
    name: "888 Design & Build",
    description: "Specializing in architecture and construction of luxury Bali villas. Combining innovative design with quality craftsmanship for your island home.",
    category: "construction",
    subcategory: "residential",
    location: "Canggu",
    address: "Jl. Raya Canggu No.88, Canggu, Kec. Kuta Utara, Kabupaten Badung, Bali 80351",
    isPro: false,
    rating: 4.3,
    reviewCount: 22,
    projects: 45,
    teamSize: 20,
    bookmarkCount: 28,
    viewsLastMonth: 680,
    imageUrl: "/images/companies/888-design-build.jpg",
  },
  {
    name: "Karyanusa Asia",
    description: "#1 Construction Company in Bali. Modern Balinese architecture with full-service offerings including architecture, interior design, and construction. Phone: +62 818 0388 8872",
    category: "construction",
    subcategory: "commercial",
    location: "Denpasar",
    address: "Jl. Imam Bonjol No.380, Pemecutan Klod, Kec. Denpasar Bar., Kota Denpasar, Bali 80119",
    isPro: true,
    rating: 4.8,
    reviewCount: 55,
    projects: 150,
    teamSize: 60,
    bookmarkCount: 72,
    viewsLastMonth: 1800,
    imageUrl: "/images/companies/karyanusa.jpg",
  },
  {
    name: "POPULAIRE",
    description: "Bali's #1 Custom Home Builder and Architectural Firm. Creating bespoke luxury residences with meticulous attention to detail and world-class design standards.",
    category: "construction",
    subcategory: "residential",
    location: "Seminyak",
    address: "Jl. Petitenget No.12, Kerobokan Kelod, Kec. Kuta Utara, Kabupaten Badung, Bali 80361",
    isPro: true,
    rating: 4.9,
    reviewCount: 48,
    projects: 95,
    teamSize: 40,
    bookmarkCount: 65,
    viewsLastMonth: 1600,
    imageUrl: "/images/companies/populaire.png",
  },
  // ARCHITECTURE
  {
    name: "Earth Lines Architects",
    description: "Architecture and interior design firm working on international residential and commercial projects. Blending contemporary design with tropical living.",
    category: "architecture",
    subcategory: "residential",
    location: "Denpasar",
    address: "Jl. Tukad Badung No.15, Renon, Kec. Denpasar Sel., Kota Denpasar, Bali 80234",
    isPro: false,
    rating: 4.4,
    reviewCount: 18,
    projects: 55,
    teamSize: 15,
    bookmarkCount: 22,
    viewsLastMonth: 520,
    imageUrl: "/images/companies/earth-lines.jpg",
  },
  {
    name: "IBUKU",
    description: "Iconic bamboo architecture firm based in Ubud. Built the world-famous Green School and Green Village. Globally recognized for pushing boundaries in sustainable bamboo construction.",
    category: "architecture",
    subcategory: "commercial",
    location: "Ubud",
    address: "Br. Tanggayuda, Kedewatan, Kec. Ubud, Kabupaten Gianyar, Bali 80571",
    isPro: true,
    rating: 4.9,
    reviewCount: 60,
    projects: 80,
    teamSize: 55,
    bookmarkCount: 95,
    viewsLastMonth: 2200,
    imageUrl: "/images/companies/ibuku.png",
  },
  {
    name: "Studio Jencquel",
    description: "Founded by German-French designer Maximilian Jencquel. Architecture and interior design studio creating spaces that harmonize with Bali's natural landscape.",
    category: "architecture",
    subcategory: "residential",
    location: "Ubud",
    address: "Jl. Raya Sayan, Sayan, Kec. Ubud, Kabupaten Gianyar, Bali 80571",
    isPro: false,
    rating: 4.6,
    reviewCount: 15,
    projects: 30,
    teamSize: 12,
    bookmarkCount: 35,
    viewsLastMonth: 780,
    imageUrl: "/images/companies/studio-jencquel.jpg",
  },
  {
    name: "Cipta Bali Architect",
    description: "Architecture firm and building contractor led by principal Made Sucipta Rokana. Delivering innovative and culturally sensitive designs across Bali.",
    category: "architecture",
    subcategory: "residential",
    location: "Denpasar",
    address: "Jl. Pulau Galang No.8, Dauh Puri Klod, Kec. Denpasar Bar., Kota Denpasar, Bali 80114",
    isPro: false,
    rating: 4.2,
    reviewCount: 12,
    projects: 40,
    teamSize: 18,
    bookmarkCount: 15,
    viewsLastMonth: 390,
    imageUrl: "/images/companies/cipta-bali.png",
  },
  {
    name: "Lumbung Architect",
    description: "Founded by I Gusti Ngurah Andri Saputra with 15+ years of experience. Team of approximately 67 professionals specializing in Balinese traditional architecture with modern sensibility.",
    category: "architecture",
    subcategory: "residential",
    location: "Ubud",
    address: "Jl. Raya Andong No.22, Petulu, Kec. Ubud, Kabupaten Gianyar, Bali 80571",
    isPro: true,
    rating: 4.5,
    reviewCount: 35,
    projects: 130,
    teamSize: 67,
    bookmarkCount: 48,
    viewsLastMonth: 950,
    imageUrl: "/images/companies/lumbung.png",
  },
  // INTERIOR DESIGN
  {
    name: "Bali Design Solutions",
    description: "Western-managed interior and architectural studio led by Managing Director Andrew De Jong with 25+ years of experience. Professional bespoke design services.",
    category: "interior",
    subcategory: "residential",
    location: "Denpasar",
    address: "Jl. Gn. Mas No.34X, Padangsambian Klod, Kec. Denpasar Bar., Kota Denpasar, Bali 80117",
    isPro: true,
    rating: 4.6,
    reviewCount: 30,
    projects: 95,
    teamSize: 22,
    bookmarkCount: 38,
    viewsLastMonth: 870,
    imageUrl: "/images/companies/bali-design-solutions.png",
  },
  {
    name: "Design Assembly",
    description: "Boutique studio established in 2015 offering architecture, interiors, and branding services. Creating cohesive design experiences across disciplines.",
    category: "interior",
    subcategory: "commercial",
    location: "Kerobokan",
    address: "Jl. Bumbak No.27, Kerobokan, Kec. Kuta Utara, Kabupaten Badung, Bali 80361",
    isPro: false,
    rating: 4.4,
    reviewCount: 16,
    projects: 42,
    teamSize: 10,
    bookmarkCount: 20,
    viewsLastMonth: 460,
    imageUrl: "/images/companies/design-assembly.jpg",
  },
  {
    name: "Mahallati Interior",
    description: "International interior design, manufacturing and production firm. Full-service from concept to completion with in-house manufacturing capabilities.",
    category: "interior",
    subcategory: "hospitality",
    location: "Denpasar",
    address: "Jl. Bypass Ngurah Rai No.100, Sanur, Kec. Denpasar Sel., Kota Denpasar, Bali 80228",
    isPro: true,
    rating: 4.7,
    reviewCount: 28,
    projects: 110,
    teamSize: 50,
    bookmarkCount: 42,
    viewsLastMonth: 1050,
    imageUrl: "/images/companies/mahallati.jpg",
  },
  {
    name: "Azula Designs",
    description: "Boutique interior design studio bringing curated tropical aesthetics to villas, hotels, and private residences throughout Bali.",
    category: "interior",
    subcategory: "residential",
    location: "Canggu",
    address: "Jl. Pantai Batu Bolong No.45, Canggu, Kec. Kuta Utara, Kabupaten Badung, Bali 80351",
    isPro: false,
    rating: 4.1,
    reviewCount: 8,
    projects: 25,
    teamSize: 6,
    bookmarkCount: 12,
    viewsLastMonth: 310,
    imageUrl: "/images/companies/azula-designs.jpg",
  },
  {
    name: "Canggu & Co",
    description: "Working with architects, renovators, and property developers to create stunning Bali interior design themes. Turnkey interior solutions for island living.",
    category: "interior",
    subcategory: "residential",
    location: "Canggu",
    address: "Jl. Raya Canggu No.52, Canggu, Kec. Kuta Utara, Kabupaten Badung, Bali 80351",
    isPro: false,
    rating: 4.0,
    reviewCount: 10,
    projects: 35,
    teamSize: 8,
    bookmarkCount: 14,
    viewsLastMonth: 350,
    imageUrl: "/images/companies/canggu-co.jpg",
  },
  // RENOVATION
  {
    name: "NC Eco Design Studio",
    description: "Architecture, landscape and green building designs. Professional and bespoke services focused on sustainable and environmentally responsible design solutions in Bali.",
    category: "renovation",
    subcategory: "complete",
    location: "Denpasar",
    address: "Jl. Tukad Barito No.18, Panjer, Kec. Denpasar Sel., Kota Denpasar, Bali 80225",
    isPro: false,
    rating: 4.3,
    reviewCount: 11,
    projects: 28,
    teamSize: 9,
    bookmarkCount: 10,
    viewsLastMonth: 280,
    imageUrl: "/images/companies/nc-eco-design.png",
  },
  {
    name: "Bali Renovation Pro",
    description: "Full-service renovation specialists for villas and homes throughout Bali. Expert in bathroom, kitchen, and complete house renovations with transparent pricing and quality workmanship.",
    category: "renovation",
    subcategory: "complete",
    location: "Seminyak",
    address: "Jl. Sunset Road No.88, Seminyak, Kec. Kuta, Kabupaten Badung, Bali 80361",
    isPro: true,
    rating: 4.6,
    reviewCount: 32,
    projects: 75,
    teamSize: 25,
    bookmarkCount: 42,
    viewsLastMonth: 890,
    imageUrl: "/images/companies/bali-construction.png",
  },
  {
    name: "Tropical Home Renovations",
    description: "Specializing in villa and home renovations including electrical, plumbing, tiling, painting, and waterproofing. Bringing new life to Bali properties with expert craftsmanship.",
    category: "renovation",
    subcategory: "bathroom",
    location: "Canggu",
    address: "Jl. Raya Canggu No.128, Canggu, Kec. Kuta Utara, Kabupaten Badung, Bali 80351",
    isPro: false,
    rating: 4.4,
    reviewCount: 18,
    projects: 45,
    teamSize: 12,
    bookmarkCount: 28,
    viewsLastMonth: 520,
    imageUrl: "/images/companies/populaire.png",
  },
  {
    name: "Villa Refresh Bali",
    description: "Expert renovation services for swimming pools, roofing, mold treatment, and complete property makeovers. Trusted by villa owners across Bali for quality renovations.",
    category: "renovation",
    subcategory: "pool",
    location: "Ubud",
    address: "Jl. Raya Ubud No.45, Ubud, Kec. Ubud, Kabupaten Gianyar, Bali 80571",
    isPro: false,
    rating: 4.2,
    reviewCount: 14,
    projects: 38,
    teamSize: 10,
    bookmarkCount: 22,
    viewsLastMonth: 410,
    imageUrl: "/images/companies/ibuku.png",
  },
  // REAL ESTATE
  {
    name: "Mirah Investment & Development",
    description: "Bali's leading property developer with almost two decades of experience. Specializing in luxury villas and resorts across the island's most prestigious locations.",
    category: "real-estate",
    subcategory: "commercial",
    location: "Seminyak",
    address: "Jl. Kayu Aya No.68, Seminyak, Kec. Kuta, Kabupaten Badung, Bali 80361",
    isPro: true,
    rating: 4.8,
    reviewCount: 45,
    projects: 200,
    teamSize: 55,
    bookmarkCount: 80,
    viewsLastMonth: 1900,
    imageUrl: "/images/companies/mirah.jpg",
  },
  {
    name: "COCO Development Group",
    description: "Full-service real estate investment, property management, and tax handling. Helping investors navigate Bali's property market with confidence.",
    category: "real-estate",
    subcategory: "commercial",
    location: "Seminyak",
    address: "Jl. Raya Petitenget No.88, Kerobokan Kelod, Kec. Kuta Utara, Kabupaten Badung, Bali 80361",
    isPro: false,
    rating: 4.2,
    reviewCount: 14,
    projects: 60,
    teamSize: 15,
    bookmarkCount: 18,
    viewsLastMonth: 520,
    imageUrl: "/images/companies/coco-development.jpg",
  },
  {
    name: "Lyvin Properties",
    description: "Premier real estate developer with top ratings on Airbnb and Booking.com. Building investment-grade properties that deliver exceptional returns.",
    category: "real-estate",
    subcategory: "residential",
    location: "Pecatu",
    address: "Jl. Bangbang Metuug, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",
    isPro: false,
    rating: 4.5,
    reviewCount: 20,
    projects: 40,
    teamSize: 18,
    bookmarkCount: 25,
    viewsLastMonth: 640,
    imageUrl: "/images/companies/lyvin.jpg",
  },
  {
    name: "Ciputra Group",
    description: "Over 40 years of experience in large-scale development projects. Currently building Ciputra Beach Resort Tabanan on 80 hectares of prime beachfront land.",
    category: "real-estate",
    subcategory: "commercial",
    location: "Tabanan",
    address: "Jl. Raya Tanah Lot, Beraban, Kec. Kediri, Kabupaten Tabanan, Bali 82121",
    isPro: true,
    rating: 4.6,
    reviewCount: 52,
    projects: 180,
    teamSize: 70,
    bookmarkCount: 90,
    viewsLastMonth: 2100,
    imageUrl: "/images/companies/ciputra.png",
  },
];

// Reviews per company (2-3 each, indexed by company name)
const reviewsMap: Record<string, { userName: string; rating: number; content: string }[]> = {
  "Balitecture": [
    { userName: "Sarah Mitchell", rating: 5, content: "Balitecture managed our entire villa build from start to finish. The Australian management style combined with local expertise made communication effortless. Our Seminyak villa was completed on schedule and the rental management service has been fantastic." },
    { userName: "James Cooper", rating: 4, content: "Professional team that really understands what expats want in a Bali property. Minor delays due to rainy season but they kept us informed throughout. The end result exceeded expectations." },
    { userName: "Komang Wijaya", rating: 5, content: "Best developer I've worked with in Bali. Their attention to detail on finishes and materials is outstanding." },
  ],
  "Bali Construction": [
    { userName: "David Chen", rating: 5, content: "Built our 4-bedroom luxury villa in Uluwatu. The team of architects and contractors worked seamlessly together. Quality of concrete work and joinery was exceptional for Bali standards." },
    { userName: "Putu Sari", rating: 4, content: "Reliable construction company with good project management. They handled all permits and approvals which saved us enormous headaches." },
  ],
  "888 Design & Build": [
    { userName: "Michael Torres", rating: 4, content: "Good design-build firm for villa construction in Bali. They handled both the architectural plans and the build which streamlined the process considerably." },
    { userName: "Wayan Sudiarta", rating: 5, content: "Very creative designs that maximize tropical living. Our villa has amazing natural ventilation and the open-plan layout is perfect for Bali's climate." },
  ],
  "Karyanusa Asia": [
    { userName: "Robert Fischer", rating: 5, content: "Karyanusa delivered our commercial project in Denpasar ahead of schedule. Their modern Balinese design approach created a building that stands out while respecting local architecture. Truly the #1 construction company in Bali." },
    { userName: "Ni Luh Putu Ratna", rating: 5, content: "Full-service experience was seamless. From architecture through interior design to final construction, one team handled everything. Highly professional." },
    { userName: "Thomas Weber", rating: 4, content: "Excellent construction quality and very responsive project managers. The scale of projects they can handle is impressive for a Bali-based firm." },
  ],
  "POPULAIRE": [
    { userName: "Alexandra Dumont", rating: 5, content: "POPULAIRE built our custom dream home in Bali and it's absolutely stunning. Every detail was considered, from the imported stone to the custom ironwork. They truly are Bali's premier custom home builder." },
    { userName: "Chris Anderson", rating: 5, content: "World-class architectural design combined with excellent construction management. The level of finish rivals anything you'd find in Australia or Singapore." },
    { userName: "Made Rai Suardana", rating: 5, content: "Working with POPULAIRE was an incredible experience. They push design boundaries while maintaining the highest build standards." },
  ],
  "Earth Lines Architects": [
    { userName: "Elena Rossi", rating: 4, content: "Earth Lines designed a beautiful contemporary villa for us that works perfectly with Bali's tropical climate. Great use of natural materials and cross-ventilation." },
    { userName: "I Wayan Karta", rating: 5, content: "Professional architecture firm with genuine international experience. Their commercial project designs are sophisticated and functional." },
  ],
  "IBUKU": [
    { userName: "Linda Park", rating: 5, content: "IBUKU's bamboo architecture is truly world-class. We visited Green Village and were blown away — then hired them for our own project. The structures are engineering marvels that feel completely organic." },
    { userName: "Sebastian Wolff", rating: 5, content: "There is simply no one else doing what IBUKU does with bamboo. The Green School is an architectural wonder and their residential work is equally breathtaking. Visionary firm." },
    { userName: "Ketut Ariani", rating: 5, content: "Proud that this globally recognized firm is based right here in Ubud. Their bamboo structures have put Bali on the map for sustainable architecture." },
  ],
  "Studio Jencquel": [
    { userName: "Marie Beaumont", rating: 5, content: "Maximilian Jencquel's designs are pure magic — raw concrete meets tropical jungle. Our Ubud residence feels like a sculptural art piece that's also incredibly livable." },
    { userName: "Gede Putra", rating: 4, content: "Unique architectural vision that really captures the spirit of Ubud. The way they integrate buildings with the landscape is remarkable." },
  ],
  "Cipta Bali Architect": [
    { userName: "John McKenzie", rating: 4, content: "Cipta Bali Architect handled both the design and construction of our Denpasar office. Made Sucipta Rokana was personally involved and brought great insight into local building regulations." },
    { userName: "Nyoman Surya", rating: 4, content: "Solid architecture firm with strong construction capabilities. They understand the nuances of building in Bali — from soil conditions to seismic requirements." },
    { userName: "Patricia Holm", rating: 5, content: "Very culturally sensitive designs that incorporate traditional Balinese elements beautifully. Great value for the quality of work." },
  ],
  "Lumbung Architect": [
    { userName: "Richard Hayes", rating: 5, content: "Lumbung Architect's team of 67 professionals delivered our resort project flawlessly. I Gusti Ngurah Andri Saputra's vision for modern Balinese architecture is inspiring. 15 years of experience shows in every detail." },
    { userName: "Wayan Merta", rating: 4, content: "The largest architecture team in Ubud and they use that scale to deliver complex projects efficiently. Their traditional Balinese design knowledge is unmatched." },
    { userName: "Sophie Laurent", rating: 5, content: "Beautiful traditional Balinese architecture with all modern amenities thoughtfully integrated. The team's depth of knowledge about local materials is impressive." },
  ],
  "Bali Design Solutions": [
    { userName: "Mark Thompson", rating: 5, content: "Andrew De Jong and his team at Bali Design Solutions transformed our villa interior completely. 25 years of experience in Bali really shows — they know every supplier and artisan on the island." },
    { userName: "Kadek Sutrisna", rating: 4, content: "Western management standards with deep local knowledge. They sourced incredible custom furniture and the project was managed professionally from start to finish." },
    { userName: "Emma Richardson", rating: 5, content: "Outstanding interior design that perfectly balances tropical elegance with practical living. Their network of local craftsmen produces furniture of remarkable quality." },
  ],
  "Design Assembly": [
    { userName: "Olivia Stark", rating: 4, content: "Design Assembly created a cohesive brand and interior for our boutique hotel in Kerobokan. Their multidisciplinary approach — architecture, interiors, and branding — gave us a unified vision." },
    { userName: "I Made Arka", rating: 5, content: "Creative boutique studio with fresh ideas. They brought a contemporary edge to our traditional Balinese space while keeping it warm and inviting." },
  ],
  "Mahallati Interior": [
    { userName: "Victoria Ling", rating: 5, content: "Mahallati's in-house manufacturing is a game-changer. They designed and produced all custom furniture for our 20-room resort. The quality control from having everything under one roof is exceptional." },
    { userName: "Ahmad Faisal", rating: 5, content: "International-quality interior design with Bali manufacturing prices. Their production facility produces stunning custom pieces that would cost 5x anywhere else." },
    { userName: "Catherine Moore", rating: 4, content: "Professional firm with impressive portfolio of hospitality projects. Their manufacturing capabilities set them apart from other design studios in Bali." },
  ],
  "Azula Designs": [
    { userName: "Rachel Green", rating: 4, content: "Azula Designs created a beautiful tropical-modern interior for our Canggu villa. Great eye for color and texture, and they source unique pieces from local artisans." },
    { userName: "Putu Laksmi", rating: 4, content: "Boutique studio with a personal touch. They really listened to what we wanted and delivered a space that feels uniquely ours." },
  ],
  "Canggu & Co": [
    { userName: "Tom Bradley", rating: 4, content: "Canggu & Co coordinated between our architect and builder to deliver cohesive interiors. Their Bali design theme expertise helped us create an authentic tropical home." },
    { userName: "Ni Kadek Dewi", rating: 4, content: "Good interior design service that works well with other professionals on the project. They understand the Bali lifestyle and design accordingly." },
  ],
  "NC Eco Design Studio": [
    { userName: "Henrik Johansson", rating: 4, content: "NC Eco Design Studio renovated our older Bali villa with sustainable materials and green building principles. The landscaping they designed is thriving and requires minimal maintenance." },
    { userName: "Made Suryawan", rating: 5, content: "Outstanding eco-friendly renovation work. They specified bamboo, recycled teak, and natural stone that transformed our property while minimizing environmental impact." },
    { userName: "Lisa Bergman", rating: 4, content: "Professional and bespoke renovation services. Their green building knowledge is genuine and they helped us achieve real energy savings." },
  ],
  "Bali Renovation Pro": [
    { userName: "Jessica Martinez", rating: 5, content: "Bali Renovation Pro completely transformed our dated villa in Seminyak. Their team handled everything from new bathrooms to a modern kitchen with transparent pricing and excellent project management." },
    { userName: "Putu Wirawan", rating: 4, content: "Professional renovation team with quality workmanship. They kept our villa rental running with minimal disruption during the renovation." },
    { userName: "Daniel Foster", rating: 5, content: "Outstanding complete house renovation service. The team's attention to detail and finishing quality exceeded expectations." },
  ],
  "Tropical Home Renovations": [
    { userName: "Amanda Chen", rating: 4, content: "Great bathroom and kitchen renovation work in our Canggu villa. Expert tiling and plumbing work that has held up perfectly." },
    { userName: "Wayan Sudira", rating: 5, content: "Tropical Home Renovations solved our waterproofing issues and gave our property a complete refresh. Highly recommended for villa renovations." },
  ],
  "Villa Refresh Bali": [
    { userName: "Marcus Berg", rating: 4, content: "Villa Refresh renovated our pool and fixed persistent mold problems. Professional team that delivered exactly what they promised." },
    { userName: "Ni Luh Ayu", rating: 4, content: "Good renovation specialists for older villas. Their roofing and waterproofing work was excellent." },
  ],
  "Mirah Investment & Development": [
    { userName: "George Williams", rating: 5, content: "Mirah Development's luxury villas are the gold standard in Bali real estate. Almost two decades of experience shows in their choice of locations, build quality, and resort-level amenities." },
    { userName: "Agung Pratama", rating: 5, content: "Bali's most trusted property developer. Their track record spanning nearly 20 years speaks for itself. Every project maintains exceptional standards." },
    { userName: "Diana Hartley", rating: 4, content: "Premium developer with premium results. The villa we purchased has appreciated significantly and the build quality remains impeccable years later." },
  ],
  "COCO Development Group": [
    { userName: "Steven Clark", rating: 4, content: "COCO handled our property investment from purchase through renovation to rental management. Their tax handling service saved us from navigating Indonesian bureaucracy alone." },
    { userName: "Wayan Budiarsa", rating: 4, content: "Good all-round property development and management company. They simplified the complexities of foreign property investment in Bali." },
  ],
  "Lyvin Properties": [
    { userName: "Andrew Phillips", rating: 5, content: "Lyvin Properties built investment villas that immediately earned Superhost status on Airbnb. Their understanding of what guests want translates directly to rental income. The Pecatu location is perfect." },
    { userName: "Ketut Sarjana", rating: 4, content: "Premier developer with a focus on ROI. Their properties consistently get top ratings on Airbnb and Booking.com which keeps occupancy high year-round." },
  ],
  "Ciputra Group": [
    { userName: "William Chang", rating: 5, content: "Ciputra's 40+ years of development experience gives unmatched confidence. The Tabanan beach resort project is going to be transformative for the area. Major infrastructure done right." },
    { userName: "I Gusti Agung Rai", rating: 4, content: "The scale of Ciputra's projects in Bali is unprecedented. Their Tabanan development covering 80 hectares shows serious commitment to the island's future." },
    { userName: "Margaret Liu", rating: 5, content: "You can't beat Ciputra's track record in Indonesian property development. Their Bali projects benefit from decades of large-scale construction expertise." },
  ],
};

export const seed = mutation({
  args: {},
  handler: async (ctx) => {
    // Clear ALL existing data
    const tables = ["savedListings", "reviews", "listings", "companies", "users"] as const;
    for (const table of tables) {
      const docs = await ctx.db.query(table).collect();
      for (const doc of docs) {
        await ctx.db.delete(doc._id);
      }
    }

    // Create a system user for seeded data
    const userId = await ctx.db.insert("users", {
      clerkId: "seed_system_user",
      email: "system@solidfind.id",
      name: "SolidFind System",
      accountType: "company",
      createdAt: Date.now(),
    });

    // Create reviewer users
    const reviewerNames = new Set<string>();
    for (const reviews of Object.values(reviewsMap)) {
      for (const r of reviews) {
        reviewerNames.add(r.userName);
      }
    }
    const reviewerUserIds: Record<string, string> = {};
    let idx = 0;
    for (const name of reviewerNames) {
      const rid = await ctx.db.insert("users", {
        clerkId: `seed_reviewer_${idx++}`,
        email: `reviewer${idx}@solidfind.id`,
        name,
        accountType: "individual",
        createdAt: Date.now(),
      });
      reviewerUserIds[name] = rid as string;
    }

    // Create companies and reviews
    for (const company of companies) {
      const companyId = await ctx.db.insert("companies", {
        ownerId: userId,
        name: company.name,
        description: company.description,
        category: company.category,
        subcategory: company.subcategory,
        location: company.location,
        address: company.address,
        isPro: company.isPro,
        rating: company.rating,
        reviewCount: company.reviewCount,
        projects: company.projects,
        teamSize: company.teamSize,
        imageUrl: company.imageUrl,
        bookmarkCount: company.bookmarkCount,
        viewsLastMonth: company.viewsLastMonth,
        projectImageIds: undefined, // Don't set fake storage IDs
        createdAt: Date.now(),
      });

      // Add reviews
      const reviews = reviewsMap[company.name] || [];
      for (let i = 0; i < reviews.length; i++) {
        const r = reviews[i];
        await ctx.db.insert("reviews", {
          companyId,
          userId: reviewerUserIds[r.userName] as any,
          userName: r.userName,
          rating: r.rating,
          content: r.content,
          createdAt: Date.now() - (i + 1) * 86400000 * 3, // spread out over time
        });
      }
    }

    return `Seeded ${companies.length} real Bali companies with reviews`;
  },
});
